license="${mod_license}"
issueTrackerURL="https://github.com/RobbertDev/InvTweaksReloaded/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="${mod_credits}"
description='''${mod_description}'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-refoxed"
logoFile="logo.png"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
